### ISSUE TITLE
Inconsistent IDE compatibility versions

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#114]
I see a warning in the Draft Release GitHub action that I think might cause a problem: 

```
> Task :setupDependencies
> Task :patchPluginXml
> Task :verifyPluginConfiguration
[gradle-intellij-plugin :radicle-jetbrains-plugin:verifyPluginConfiguration] The following plugin configuration issues were found:
- The 'since-build' property is lower than the target IntelliJ Platform major version: 203 < 222.
- The Java configuration specifies sourceCompatibility=11 but IntelliJ Platform 2022.2 requires sourceCompatibility=17.
See: https://jb.gg/intellij-platform-versions
```

Here are the 2 commits that introduced: 
* https://github.com/cytechmobile/radicle-intellij-plugin/commit/8c9b7c2b
* https://github.com/cytechmobile/radicle-intellij-plugin/commit/8686e548

**Comment by gsaslis** [comment]
@Stelios123 / @JChrist FYI

**Comment by gsaslis** [comment]
This is not a real issue, as documented on the official announcement from Jetbrains: 
https://blog.jetbrains.com/platform/2022/08/intellij-project-migrates-to-java-17/

> If you develop a plugin, you can use new language features and APIs from Java 17, but only if the since-build attribute in plugin.xml is set to 223. If your plugin distribution needs to run on multiple versions of the IDE, for example, 2022.3 and 2022.2, then you must continue to use Java 11.

**Comment by JChrist** [comment]
This is intended and works as expected.
Since we need to support intellij 203, we are limited to have source compatibility with java 11.
Intellij 222 (2022.2) has source compatibility with java 17 and this is fine, since java 17 fully supports running code with lower source compatibility.
Once we "upgrade" to support intellij 222+ only, we can increase our source compatibility to 17.
