### ISSUE TITLE
Deploy a heartwood node

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#187]
Run Locally: 

- [x] windows
- [x] macOS
- [x] linux

Questions: 
- can multiple contributors just use the CLI on their laptop and use a **common** seed node, or does every contributor need to run a node on their laptop ?
-

**Comment by gsaslis** [comment]
@JChrist if you've run this on linux, I think we can close this.

**Comment by JChrist** [comment]
Yep, everything seems to be working fine on Linux, wrt installing and running.
I had some issues with my rust/cargo setup, most probably due to my very limited knowledge.
I finally nuked everything and started from scratch.
I'll list my steps to make sure we're in-sync, as well as mini-doc on how to get started:
- Uninstall rustup and cargo: `rustup self uninstall` (Optional, but worked for me)
- Reinstall fresh rustup: `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` (Optional)
- Clone heartwood repo: `git clone git@github.com:radicle-dev/heartwood.git`
- Install radicle-cli, radicle-node and radicle-remote-helper from heartwood repo:
  * `cargo install --path radicle-cli --force --locked`
  * `cargo install --path radicle-node --force --locked`
  * `cargo install --path radicle-remote-helper --force --locked`
- Now everything should be in place, `rad --version` outputs: `rad 0.8.0`
- Create an identity: `rad auth`
- Execute `radicle-node` (which should automatically pick up the new identity).
- Invoke a few rad commands on a new repo
  * `mkdir ./test`
  * `git init`
  * `touch test.txt`
  * `git add test.txt`
  * `git commit -m 'initial'`
  * `rad init`
  * `rad .`
  * `rad push`
