### ISSUE TITLE
User Issue - Path to Rad executable unclear/not working

### ISSUE THREAD

**Issue by bordumb** [cytechmobile/radicle-jetbrains-plugin#69]
Related to #64 

Installing IDE + plug-in was fairly straightforward, so no issue there.
But showing the installation may be beneficial for others.

Dropping some issues further along the workflow that may benefit from video instruction.

### `Path to Rad executable` is unclear

I get the error below when using `/usr/local/bin/rad`:

<img width="974" alt="image" src="https://user-images.githubusercontent.com/3743841/186355606-e7a63b55-bd62-4488-a3ef-b12d03e3ea43.png">

Checking in terminal using `which rad` this path appear to be correct:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/3743841/186356015-9bfce27e-fb18-4003-8151-1d41f003ab3c.png">

More context:
* MacBook Pro M1
* IntelliJ IDEA 2022.2 (Community Edition) Build #IC-222.3345.118, built on July 26, 2022

**Comment by JChrist** [comment]
Hi @bordumb, 
thank you for the detailed issue!
Your steps seem to be perfectly fine.
The issue most probably stems from the radicle CLI version installed on your machine.
The minimum required version is 0.6.0, unfortunately not mentioned in the requirements.
The version coming from homebrew is older than that and causes this strange issue, due to the fact that older radicle cli versions do not support the `rad --version` command, which is used by the IDE plugin to determine whether the path to the CLI is correct.

I will add further instructions to the requirements section to mention this explicitly.

Work on #64 will start soon, it was delayed due to some issues occuring for Windows machines, addressed in #68.
