### ISSUE TITLE
Add "Push" sub-menu item to Git -> Radicle

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-jetbrains-plugin#8]
When we click Push, it brings up the "Git -> Push..." screen from IntelliJ and then does rad sync. 

`rad push` does `git push` and then `rad sync` - we don't want to use `rad push` in this case, because we want the native git push IDE experience.  

https://www.figma.com/proto/9h2suLnyckUXGmMyReMiYP/LF-Wireframe---Milestone-1?node-id=472119%3A11713&scaling=scale-down&page-id=77%3A432&starting-point-node-id=472119%3A11713&show-proto-sidebar=1

**Comment by JChrist** [comment]
This needs some thought and break down.
What is expected to happen when a project contains more than one git repos (with possibly only some of them being under radicle)?
Also, the expected flow is that `Radicle -> Push` opens up the `Git -> Push` dialog and if that _did push something_, only then is it followed by `rad sync` for the respective git repos.
But if the user git-pushed some other way, (e.g. by Git->Push directly)? 
Is that expected to be handled via Radicle->Synchronize ?

The other thing we should make a decision is about error handling. What is expected to happen:
- if no rad cli path is configured? (<- I have already added a warning with a `Configure` action that takes you to Radicle settings page)
- if user has not executed `rad auth`
- if rad init has not been executed for a project (or even worse, repo?)
- if there are no rad remotes configured in the repo

My thinking is that each of these should be handled with some user-friendly way, so each one should go into a separate issue. But, at least for the first deliverable, I believe a respective error notification with the actual rad cli error output should be enough (e.g. we do not have yet a way to configure the radicle profile, so that error handling cannot happen now)

**Comment by gsaslis** [comment]
As per our discussion today, developers commonly think "Git -> Push"  sends content to a **remote** server. In a radicle-initialised repository, where the `rad` remote has been set up and is the default, the content from `git push rad` hasn't been sent to the seed node (that developers expect as the corresponding remote server). 

With that in mind, we would like to find the way to:
* "listen" when a git push is made 
* if a radicle-initialised repo has been pushed to
* we want to display a popup/warning asking the developer: "Looks like you `git push`ed in a radicle-initialised project, rather than `rad push`.  Perhaps you also want to `rad sync`  ( `rad push` == `git push rad && rad sync` ) "
